# -*- coding: utf-8 -*-
"""アプリ開発.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XID3ZIRTIh_QGvrPh4IUmEn_xNBaNvwJ
"""

pip install amplify

import sys
import numpy as np
from amplify import VariableGenerator, Model, solve
from amplify import Constraint, equal_to, less_equal
from amplify import AmplifyAEClient
from amplify import sum

driver_w = [[0,0,0] for _ in range(14)]
print(driver_w)

people_map = {0: '武井', 1: '佐藤', 2: '萩原', 3: '森島', 4: '森居', 5: '松本', 6: '首藤', 7: '助川', 8: '濱家', 9: '大野', 10: '藤井', 11: '村上', 12: '南', 13: '荒木'}
car_map = {0: '阿部車', 1:'古知屋車',2: '森田車'}
C = [8, 5, 5]
d = [[45,50,23], [32,0,32], [40,2,40], [60,51,22], [56,37,10], [67,53,20], [100,97,69], [5,26,45], [32,0,32], [34,2,30], [51,8,42], [24,31,54], [48, 5, 39], [62,34,36]]
W = [[0,-10, 0, 0, 0, 0,0,0,-10,0,0,0,0,-10],[-10,0,0,0,0,0,0,0,-10,0,0,0,0,-10],[0,0,0,0,-10,0,0,-10,0,-10,0,-10,0,0],[0,0,0,0,0,0,0,0,0,0,-10,0,-10,0],
[0,0,-10,0,0,0,0,-10,0,-10,0,0,0,0],[0 for _ in range(14)], [0,0,0,0,0,0,0,0,0,0,0,-10,0,0], [0,0,-10,0,-10,0,0,0,0,-10,0,0,0,0],[-10,-10,0,0,0,0,0,0,0,0,0,0,0,-10]
     ,[0,0,-10,0,-10,0,0,-10,0,0,0,0,0,0],[0,0,0,-10,0,0,0,0,0,0,0,0,-10,0],[0,0,-10,0,0,0,-10,0,0,0,0,0,0,0],[0,0,0,-10,0,0,0,0,0,0,-10,0,0,0],[-10,-10,0,0,0,0,0,0,-10,0,0,0,0,0]]
driver_W = [[0, 0, 0], [0, 0, 0], [100, 0, 0], [-10, 0, 0], [0, 0, 0], [0, 0, 0], [0, -10, -10], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, -10, -10], [-10, 0, 0], [0, 0, 0]]

# @title −五分に設定した場合
W = [
    [ 0, -5,  0,  0,  0,  0,  0,  0, -5,  0,  0,  0,  0, -5],
    [-5,  0,  0,  0,  0,  0,  0,  0, -5,  0,  0,  0,  0, -5],
    [ 0,  0,  0,  0, -5,  0,  0, -5,  0, -5,  0, -5,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -5,  0, -5,  0],
    [ 0,  0, -5,  0,  0,  0,  0, -5,  0, -5,  0,  0,  0,  0],
    [0 for _ in range(14)],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -5,  0,  0],
    [ 0,  0, -5,  0, -5,  0,  0,  0,  0, -5,  0,  0,  0,  0],
    [-5, -5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -5],
    [ 0,  0, -5,  0, -5,  0,  0, -5,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0, -5,  0,  0,  0,  0,  0,  0,  0,  0, -5,  0],
    [ 0,  0, -5,  0,  0,  0, -5,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0, -5,  0,  0,  0,  0,  0,  0, -5,  0,  0,  0],
    [-5, -5,  0,  0,  0,  0,  0,  0, -5,  0,  0,  0,  0,  0]
]

driver_W = [
    [  0,  0,  0],
    [  0,  0,  0],
    [100,  0,  0],
    [ -5,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0, -5, -5],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0, -5, -5],
    [ -5,  0,  0],
    [  0,  0,  0]
]

#@title 仲がいいを考慮に入れなかった場合
W = [[0 for _ in range(14)] for _ in range(14)]
driver_W = [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

p = -8  # 仲の良さのスコア（許容できる遠回りの分数）

W = [
    [ 0,  p,  0,  0,  0,  0,  0,  0,  p,  0,  0,  0,  0,  p],
    [ p,  0,  0,  0,  0,  0,  0,  0,  p,  0,  0,  0,  0,  p],
    [ 0,  0,  0,  0,  p,  0,  0,  p,  0,  p,  0,  p,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  p,  0,  p,  0],
    [ 0,  0,  p,  0,  0,  0,  0,  p,  0,  p,  0,  0,  0,  0],
    [0 for _ in range(14)],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  p,  0,  0],
    [ 0,  0,  p,  0,  p,  0,  0,  0,  0,  p,  0,  0,  0,  0],
    [ p,  p,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  p],
    [ 0,  0,  p,  0,  p,  0,  0,  p,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  p,  0,  0,  0,  0,  0,  0,  0,  0,  p,  0],
    [ 0,  0,  p,  0,  0,  0,  p,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  p,  0,  0,  0,  0,  0,  0,  p,  0,  0,  0],
    [ p,  p,  0,  0,  0,  0,  0,  0,  p,  0,  0,  0,  0,  0]
]

driver_W = [
    [  0,  0,  0],
    [  0,  0,  0],
    [0,  0,  0],
    [  p,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  p,  p],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  0,  0],
    [  0,  p,  p],
    [  p,  0,  0],
    [  0,  0,  0]
]

# ==========================================
# 1. 問題設定とデータの準備
# ==========================================
# 運転手はすでに各車に固定されているため、最適化の対象(people_map)には含めません。
#people_map = {0: 'Aさん', 1: 'Bさん', 2: 'Cさん', 3: 'Dさん', 4: 'Eさん', 5: 'Fさん', 6: 'Gさん', 7: 'Hさん'}
#car_map = {0: 'アルファード', 1: 'プリウス'}

num_people = len(people_map)
num_cars = len(car_map)

# C_k: 各車の「総定員」 (例: アルファード8名、プリウス5名)
#C = [8, 5]

# ==========================================
# 2. 実行前の物理的制約（定員）チェック
# ==========================================
# 各車の総定員から運転手1名分を引いたものが、最適化エンジンが利用可能な「有効シート数」です。
total_available_seats = sum(c - 1 for c in C)

print(f"配車対象人数: {num_people}名")
print(f"有効シート数合計: {total_available_seats}席 (総定員から運転手分を除外)")

if num_people > total_available_seats:
    print("\n【エラー】有効シート数が不足しています。全員を配車することが物理的に不可能です。")
    print("車の追加、または配車対象人数の見直しを行ってください。")
    sys.exit() # 処理を終了

print("定員チェッククリア。最適化計算を開始します...\n")

# ハイパーパラメータの設定 (分析に基づく最適なバランス)
alpha = 1.0      # 移動時間の重み
beta = 1.0       # 人間関係の重み
lambda_1 = 5000.0 # One-hot制約のペナルティ重み (ハード制約)
lambda_2 = 5000.0 # 定員制約のペナルティ重み (ハード制約)

# ==========================================
# 4. 変数の定義
# ==========================================
gen = VariableGenerator()
x = gen.array("Binary", (num_people, num_cars))

# ==========================================
# 5. 目的関数（コスト）の構築
# ==========================================
distance_cost = sum(
    d[i][k] * x[i, k]
    for i in range(num_people)
    for k in range(num_cars)
)

relation_cost = sum(
    W[i][j] * x[i, k] * x[j, k]
    for i in range(num_people)
    for j in range(i + 1, num_people) # j > i
    for k in range(num_cars)
)

# (3) 【新規】運転手と乗客の人間関係コスト (一次項)
driver_relation_cost = sum(
    driver_W[i][k] * x[i, k]
    for i in range(num_people)
    for k in range(num_cars)
)

objective = alpha * distance_cost + beta * relation_cost + beta * driver_relation_cost

# ==========================================
# 6. 制約条件の構築
# ==========================================
# (1) One-hot制約: 各人は必ず1つの車に乗る
one_hot_constraints = [
    equal_to(sum(x[i, k] for k in range(num_cars)), 1)
    for i in range(num_people)
]

# (2) 定員制約: 各車の乗客数は「総定員 - 1 (運転手)」以下とする
capacity_constraints = [
    less_equal(sum(x[i, k] for i in range(num_people)), C[k] - 1)
    for k in range(num_cars)
]

constraints = sum(c * lambda_1 for c in one_hot_constraints) + \
              sum(c * lambda_2 for c in capacity_constraints)

# ==========================================
# 7. モデルの構築とマシンの実行
# ==========================================
model = Model(objective, constraints)

client = AmplifyAEClient()
# ※実環境で実行する際は、ご自身のAPIトークンを入力してください
client.token = "AE/vzQBAi2CD7Gvhp4HxckW0UFhMOt2rqsW"
client.parameters.time_limit_ms = 1000

result = solve(model, client)

# ==========================================
# 8. 結果の解析と出力
# ==========================================
if len(result) == 0:
    print("【エラー】解が見つかりませんでした。制約条件が相互に矛盾している可能性があります。")
else:
    best_solution = result[0]
    # x_opt = best_solution.values.evaluate(x)
    x_opt = x.evaluate(best_solution.values)

    print("========================================")
    print(f"最小エネルギー: {best_solution.objective}")
    print(f"制約条件の充足: {best_solution.feasible}")
    print("========================================\n")

    if not best_solution.feasible:
        print("警告: 出力された解は制約（定員オーバー等）を満たしていません。ペナルティ係数を大きくしてください。")

    print("【最適な配車結果】")
    for k in range(num_cars):
        passengers = []
        for i in range(num_people):
            if int(x_opt[i][k]) == 1:
                passengers.append(people_map[i])

        car_name = car_map[k]
        # 実際の有効定員 (C[k] - 1) もあわせて表示
        print(f"{car_name} (有効乗客枠: {C[k] - 1}名): {passengers}")

import pandas as pd
import json
import os
import googlemaps
from datetime import datetime

# ==========================================
# 設定パラメータ
# ==========================================
API_KEY = 'YOUR_GOOGLE_MAPS_API_KEY'
CACHE_FILE = 'distance_cache.json'
USAGE_FILE = 'usage_stats.json'
FIXSTARS_KEY = 'MYtoken'
MONTHLY_LIMIT = 5000
TARGET_ARRIVAL = datetime(2026, 4, 10, 9, 0) # 到着希望時間
P_SCORE = -5 # 仲が良い場合の報酬スコア

# ==========================================
# 1. データの読み込みと人間関係行列 W の自動生成
# ==========================================
def process_form_data(file_path):
    df = pd.read_csv(file_path).dropna(subset=['名前', '最寄り駅'])
    df['名前'] = df['名前'].str.strip()
    df['最寄り駅'] = df['最寄り駅'].str.strip()

    # 運転手と乗客の分割
    df_drivers = df[df['参加形態'] == '運転手']
    df_passengers = df[df['参加形態'] != '運転手']

    drivers = df_drivers['名前'].tolist()
    passengers = df_passengers['名前'].tolist()

    driver_stations = df_drivers['最寄り駅'].tolist()
    passenger_stations = df_passengers['最寄り駅'].tolist()

    # --- 人間関係行列 W の生成 ---
    # 乗客全員のリストから、名前をインデックス（数字）に変換する辞書を作成
  # --- 人間関係行列 W の生成（アップデート版） ---
    p_idx_map = {name: i for i, name in enumerate(passengers)}
    n_passengers = len(passengers)
    W = [[0] * n_passengers for _ in range(n_passengers)]

    # 【ステップ1】誰が誰をどう思っているか（一方向の感情）を記録する辞書
    # 初期値は全員 'NEUTRAL'（なんでもいい）とする
    pref = {i: {j: 'NEUTRAL' for j in range(n_passengers)} for i in range(n_passengers)}

    # スプレッドシートの回答を pref に流し込む
    for _, row in df_passengers.iterrows():
        name = row['名前']
        if name not in p_idx_map: continue
        i = p_idx_map[name]

        # 「一緒になりたい」の上書き
        if pd.notna(row.get('一緒になりたい人')):
            for friend in str(row['一緒になりたい人']).split(','):
                friend = friend.strip()
                if friend in p_idx_map:
                    pref[i][p_idx_map[friend]] = 'WANT'

        # 「気まずい」の上書き（もし同一人物を両方に書いていた場合、気まずいが勝つ設計）
        if pd.notna(row.get('気まずい人')):
            for awkward in str(row['気まずい人']).split(','):
                awkward = awkward.strip()
                if awkward in p_idx_map:
                    pref[i][p_idx_map[awkward]] = 'AWKWARD'

    # 【ステップ2】お互いの感情を突き合わせて、優先度順に最終スコア W を決定する
    # 組み合わせなので、行列の右上半分だけを計算し、左下は対象にコピーする（計算量の削減）
    for i in range(n_passengers):
        for j in range(i + 1, n_passengers):
            p1 = pref[i][j] # iさん から jさん への感情
            p2 = pref[j][i] # jさん から iさん への感情

            # 優先度1：「気まずい」が1人でもいれば、問答無用でペナルティ(100)
            if p1 == 'AWKWARD' or p2 == 'AWKWARD':
                score = 100

            # 優先度2：気まずい人がおらず、どちらか1人でも「一緒がいい」なら報酬(P_SCORE)
            elif p1 == 'WANT' or p2 == 'WANT':
                score = P_SCORE

            # 優先度3：両方とも「なんでもいい」なら影響なし(0)
            else:
                score = 0

            # 対称行列として W にスコアを代入
            W[i][j] = score
            W[j][i] = score

    return passengers, drivers, passenger_stations, driver_stations, W

# ==========================================
# 2. キャッシュ付き API 計算（前回のロジック）
# ==========================================
def load_json(filename, default):
    if os.path.exists(filename):
        with open(filename, 'r', encoding='utf-8') as f:
            return json.load(f)
    return default

def save_json(filename, data):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

def get_distance_with_cache(passengers, drivers, target_arrival):
    gmaps = googlemaps.Client(key=API_KEY)
    cache = load_json(CACHE_FILE, {})
    usage = load_json(USAGE_FILE, {"total_elements": 0})

    # ==========================================
    # 1. キャッシュにない「不足している駅」を洗い出す
    # ==========================================
    missing_passengers = []
    missing_drivers = []

    for p in passengers:
        for d in drivers:
            cache_key = f"{p}_{d}"
            if cache_key not in cache:
                # 重複を避けて不足リストに追加
                if p not in missing_passengers: missing_passengers.append(p)
                if d not in missing_drivers: missing_drivers.append(d)

    # ==========================================
    # 2. 不足分がある場合のみ、APIを実行してキャッシュを更新
    # ==========================================
    if missing_passengers and missing_drivers:
        requested_elements = len(missing_passengers) * len(missing_drivers)

        # 使用上限のチェック
        if usage["total_elements"] + requested_elements > MONTHLY_LIMIT:
            raise Exception(f"APIの使用上限に達しました。（今月: {usage['total_elements']} / 上限: {MONTHLY_LIMIT}）")

        print(f"API通信を実行中... (新規 {requested_elements} 要素)")

        # 不足している駅のリストだけでAPIを叩く
        result = gmaps.distance_matrix(
            origins=missing_passengers,
            destinations=missing_drivers,
            mode="transit",
            language="ja",
            arrival_time=target_arrival,
            transit_mode=["bus", "rail"]
        )

        # 結果をパースしてキャッシュ辞書に追加する
        for p_idx, row in enumerate(result['rows']):
            p_station = missing_passengers[p_idx]
            for d_idx, element in enumerate(row['elements']):
                d_station = missing_drivers[d_idx]
                cache_key = f"{p_station}_{d_station}"

                if element['status'] == 'OK':
                    duration_min = element['duration']['value'] // 60
                    cache[cache_key] = duration_min
                else:
                    print(f"警告: {p_station} から {d_station} への経路が見つかりません。")
                    cache[cache_key] = 999  # ペナルティ値もキャッシュに記憶させる

        # 使用量と最新のキャッシュをJSONファイルに書き込んで保存
        usage["total_elements"] += requested_elements
        save_json(USAGE_FILE, usage)
        save_json(CACHE_FILE, cache)
        print("キャッシュデータを更新・保存しました。")
    else:
        print("すべてキャッシュから読み込みました（API通信コストゼロ）。")

    # ==========================================
    # 3. 最適化ソルバー用の2次元配列（行列 d）の生成
    # ==========================================
    d_matrix = []

    # 完全なデータが揃った cache から、元の並び順で行列を作る
    for p in passengers:
        row = []
        for d in drivers:
            cache_key = f"{p}_{d}"
            row.append(cache[cache_key])
        d_matrix.append(row)

    return d_matrix

# ==========================================
# 3. Amplify による最適化実行
# ==========================================
def run_optimization(passengers, drivers, d_matrix, W):
    print("最適化ソルバーを起動します...")
    # (ここにすでに作成済みのAmplifyのコードが入ります)
    # 変数定義 -> 目的関数(d_matrix と W を使用) -> 制約条件 -> 求解

# ==========================================
# 1. 問題設定とデータの準備
# ==========================================
# 運転手はすでに各車に固定されているため、最適化の対象(people_map)には含めません。
#people_map = {0: 'Aさん', 1: 'Bさん', 2: 'Cさん', 3: 'Dさん', 4: 'Eさん', 5: 'Fさん', 6: 'Gさん', 7: 'Hさん'}
#car_map = {0: 'アルファード', 1: 'プリウス'}

num_people = len(people_map)
num_cars = len(car_map)

# C_k: 各車の「総定員」 (例: アルファード8名、プリウス5名)
#C = [8, 5]

# ==========================================
# 2. 実行前の物理的制約（定員）チェック
# ==========================================
# 各車の総定員から運転手1名分を引いたものが、最適化エンジンが利用可能な「有効シート数」です。
total_available_seats = sum(c - 1 for c in C)

print(f"配車対象人数: {num_people}名")
print(f"有効シート数合計: {total_available_seats}席 (総定員から運転手分を除外)")

if num_people > total_available_seats:
    print("\n【エラー】有効シート数が不足しています。全員を配車することが物理的に不可能です。")
    print("車の追加、または配車対象人数の見直しを行ってください。")
    sys.exit() # 処理を終了

print("定員チェッククリア。最適化計算を開始します...\n")

# ハイパーパラメータの設定 (分析に基づく最適なバランス)
alpha = 1.0      # 移動時間の重み
beta = 1.0       # 人間関係の重み
lambda_1 = 5000.0 # One-hot制約のペナルティ重み (ハード制約)
lambda_2 = 5000.0 # 定員制約のペナルティ重み (ハード制約)

# ==========================================
# 4. 変数の定義
# ==========================================
gen = VariableGenerator()
x = gen.array("Binary", (num_people, num_cars))

# ==========================================
# 5. 目的関数（コスト）の構築
# ==========================================
distance_cost = sum(
    d[i][k] * x[i, k]
    for i in range(num_people)
    for k in range(num_cars)
)

relation_cost = sum(
    W[i][j] * x[i, k] * x[j, k]
    for i in range(num_people)
    for j in range(i + 1, num_people) # j > i
    for k in range(num_cars)
)

# (3) 【新規】運転手と乗客の人間関係コスト (一次項)
driver_relation_cost = sum(
    driver_W[i][k] * x[i, k]
    for i in range(num_people)
    for k in range(num_cars)
)

objective = alpha * distance_cost + beta * relation_cost + beta * driver_relation_cost

# ==========================================
# 6. 制約条件の構築
# ==========================================
# (1) One-hot制約: 各人は必ず1つの車に乗る
one_hot_constraints = [
    equal_to(sum(x[i, k] for k in range(num_cars)), 1)
    for i in range(num_people)
]

# (2) 定員制約: 各車の乗客数は「総定員 - 1 (運転手)」以下とする
capacity_constraints = [
    less_equal(sum(x[i, k] for i in range(num_people)), C[k] - 1)
    for k in range(num_cars)
]

constraints = sum(c * lambda_1 for c in one_hot_constraints) + \
              sum(c * lambda_2 for c in capacity_constraints)

# ==========================================
# 7. モデルの構築とマシンの実行
# ==========================================
model = Model(objective, constraints)

client = FixstarsClient()
# ※実環境で実行する際は、ご自身のAPIトークンを入力してください
client.token = FIXSTARS_KEY
client.parameters.timeout = 1500

result = solve(model, client)

# ==========================================
# 8. 結果の解析と出力
# ==========================================
if len(result) == 0:
    print("【エラー】解が見つかりませんでした。制約条件が相互に矛盾している可能性があります。")
else:
    best_solution = result[0]
    # x_opt = best_solution.values.evaluate(x)
    x_opt = x.evaluate(best_solution.values)

    print("========================================")
    print(f"最小エネルギー: {best_solution.objective}")
    print(f"制約条件の充足: {best_solution.feasible}")
    print("========================================\n")

    if not best_solution.feasible:
        print("警告: 出力された解は制約（定員オーバー等）を満たしていません。ペナルティ係数を大きくしてください。")

    print("【最適な配車結果】")
    result_align_list = []
    for k in range(num_cars):
        passengers = []
        for i in range(num_people):
            if int(x_opt[i][k]) == 1:
                passengers.append(people_map[i])

        car_name = car_map[k]
        # 実際の有効定員 (C[k] - 1) もあわせて表示

        print(f"{car_name} (有効乗客枠: {C[k] - 1}名): {passengers}")



# ==========================================
# メイン実行ブロック
# ==========================================
if __name__ == "__main__":
    print("--- システム処理開始 ---")

    # 1. データ抽出
    passengers, drivers, p_stations, d_stations, W = process_form_data('form_responses.csv')

    # 2. API計算
    d_matrix = get_distance_matrix(p_stations, d_stations, TARGET_ARRIVAL)

    # 3. 最適化計算
    result = run_optimization(passengers, drivers, d_matrix, W)

    # 4. 結果出力
    print("\n--- 最終出力 ---")
    print(result)

import pandas as pd
import json
import os
import sys
import googlemaps
from datetime import datetime

# --- Amplifyモジュールのインポート（必須） ---
from amplify import VariableGenerator, Model, solve, equal_to, less_equal
from amplify.client import FixstarsClient

# ==========================================
# 設定パラメータ
# ==========================================
API_KEY = 'YOUR_GOOGLE_MAPS_API_KEY'
CACHE_FILE = 'distance_cache.json'
USAGE_FILE = 'usage_stats.json'
FIXSTARS_KEY = 'MYtoken'
MONTHLY_LIMIT = 5000
TARGET_ARRIVAL = datetime(2026, 4, 10, 9, 0)
P_SCORE = -5

# ==========================================
# 1. データの読み込みと人間関係行列 W の生成
# ==========================================
def process_form_data(file_path):
    df = pd.read_csv(file_path).dropna(subset=['名前', '最寄り駅'])
    df['名前'] = df['名前'].str.strip()
    df['最寄り駅'] = df['最寄り駅'].str.strip()

    df_drivers = df[df['参加形態'] == '運転手']
    df_passengers = df[df['参加形態'] != '運転手']

    drivers = df_drivers['名前'].tolist()
    passengers = df_passengers['名前'].tolist()

    driver_stations = df_drivers['最寄り駅'].tolist()
    passenger_stations = df_passengers['最寄り駅'].tolist()

    p_idx_map = {name: i for i, name in enumerate(passengers)}
    n_passengers = len(passengers)
    W = [[0] * n_passengers for _ in range(n_passengers)]
    pref = {i: {j: 'NEUTRAL' for j in range(n_passengers)} for i in range(n_passengers)}

    for _, row in df_passengers.iterrows():
        name = row['名前']
        if name not in p_idx_map: continue
        i = p_idx_map[name]

        if pd.notna(row.get('一緒になりたい人')):
            for friend in str(row['一緒になりたい人']).split(','):
                friend = friend.strip()
                if friend in p_idx_map:
                    pref[i][p_idx_map[friend]] = 'WANT'

        if pd.notna(row.get('気まずい人')):
            for awkward in str(row['気まずい人']).split(','):
                awkward = awkward.strip()
                if awkward in p_idx_map:
                    pref[i][p_idx_map[awkward]] = 'AWKWARD'

    for i in range(n_passengers):
        for j in range(i + 1, n_passengers):
            p1 = pref[i][j]
            p2 = pref[j][i]
            if p1 == 'AWKWARD' or p2 == 'AWKWARD':
                score = 100
            elif p1 == 'WANT' or p2 == 'WANT':
                score = P_SCORE
            else:
                score = 0
            W[i][j] = score
            W[j][i] = score

    return passengers, drivers, passenger_stations, driver_stations, W

# ==========================================
# 2. キャッシュ付き API 計算
# ==========================================
def load_json(filename, default):
    if os.path.exists(filename):
        with open(filename, 'r', encoding='utf-8') as f:
            return json.load(f)
    return default

def save_json(filename, data):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

def get_distance_with_cache(passengers, drivers, target_arrival):
    gmaps = googlemaps.Client(key=API_KEY)
    cache = load_json(CACHE_FILE, {})
    usage = load_json(USAGE_FILE, {"total_elements": 0})

    missing_passengers = []
    missing_drivers = []

    for p in passengers:
        for d in drivers:
            cache_key = f"{p}_{d}"
            if cache_key not in cache:
                if p not in missing_passengers: missing_passengers.append(p)
                if d not in missing_drivers: missing_drivers.append(d)

    if missing_passengers and missing_drivers:
        requested_elements = len(missing_passengers) * len(missing_drivers)
        if usage["total_elements"] + requested_elements > MONTHLY_LIMIT:
            raise Exception(f"APIの使用上限に達しました。")

        print(f"API通信を実行中... (新規 {requested_elements} 要素)")

        result = gmaps.distance_matrix(
            origins=missing_passengers,
            destinations=missing_drivers,
            mode="transit",
            language="ja",
            arrival_time=target_arrival,
            transit_mode=["bus", "rail"]
        )

        for p_idx, row in enumerate(result['rows']):
            p_station = missing_passengers[p_idx]
            for d_idx, element in enumerate(row['elements']):
                d_station = missing_drivers[d_idx]
                cache_key = f"{p_station}_{d_station}"

                if element['status'] == 'OK':
                    duration_min = element['duration']['value'] // 60
                    cache[cache_key] = duration_min
                else:
                    cache[cache_key] = 999

        usage["total_elements"] += requested_elements
        save_json(USAGE_FILE, usage)
        save_json(CACHE_FILE, cache)

    d_matrix = []
    for p in passengers:
        row = []
        for d in drivers:
            cache_key = f"{p}_{d}"
            row.append(cache[cache_key])
        d_matrix.append(row)

    return d_matrix

# ==========================================
# 3. Amplify による最適化実行
# ==========================================
def run_optimization(passengers, drivers, d_matrix, W):
    print("最適化ソルバーを起動します...")

    # 辞書マッピングの自動生成
    people_map = {i: name for i, name in enumerate(passengers)}
    car_map = {k: name for k, name in enumerate(drivers)}

    num_people = len(people_map)
    num_cars = len(car_map)

    # ※要確認：各車の定員と、乗客-運転手間の関係性の設定
    # 今回はダミー値として、各車の定員を5名、運転手との関係性を全て0と設定
    C = [5 for _ in range(num_cars)]
    driver_W = [[0] * num_cars for _ in range(num_people)]

    total_available_seats = sum(c - 1 for c in C)

    if num_people > total_available_seats:
        return "【エラー】有効シート数が不足しています。全員を配車することが物理的に不可能です。"

    alpha = 1.0
    beta = 1.0
    lambda_1 = 5000.0
    lambda_2 = 5000.0

    gen = VariableGenerator()
    x = gen.array("Binary", (num_people, num_cars))

    distance_cost = sum(
        d_matrix[i][k] * x[i, k]
        for i in range(num_people)
        for k in range(num_cars)
    )

    relation_cost = sum(
        W[i][j] * x[i, k] * x[j, k]
        for i in range(num_people)
        for j in range(i + 1, num_people)
        for k in range(num_cars)
    )

    driver_relation_cost = sum(
        driver_W[i][k] * x[i, k]
        for i in range(num_people)
        for k in range(num_cars)
    )

    objective = alpha * distance_cost + beta * relation_cost + beta * driver_relation_cost

    one_hot_constraints = [
        equal_to(sum(x[i, k] for k in range(num_cars)), 1)
        for i in range(num_people)
    ]

    capacity_constraints = [
        less_equal(sum(x[i, k] for i in range(num_people)), C[k] - 1)
        for k in range(num_cars)
    ]

    constraints = sum(c * lambda_1 for c in one_hot_constraints) + \
                  sum(c * lambda_2 for c in capacity_constraints)

    model = Model(objective, constraints)
    client = AmplifyAEClient()
    client.token = FIXSTARS_KEY
    client.parameters.time_limit_ms = 1500

    result = solve(model, client)

    if len(result) == 0:
        return "【エラー】解が見つかりませんでした。制約条件が相互に矛盾している可能性があります。"

    best_solution = result[0]
    x_opt = x.evaluate(best_solution.values)

    output_text = f"最小エネルギー: {best_solution.objective}\n制約条件の充足: {best_solution.feasible}\n\n【最適な配車結果】\n"

    for k in range(num_cars):
        p_list = []
        for i in range(num_people):
            if int(x_opt[i][k]) == 1:
                p_list.append(people_map[i])
        output_text += f"{car_map[k]}号車 (有効乗客枠: {C[k] - 1}名): {p_list}\n"

    return output_text

# ==========================================
# メイン実行ブロック
# ==========================================
if __name__ == "__main__":
    print("--- システム処理開始 ---")

    # 1. データ抽出
    passengers, drivers, p_stations, d_stations, W = process_form_data('form_responses.csv')

    # 2. API計算 (関数名を正しいものに修正)
    d_matrix = get_distance_with_cache(p_stations, d_stations, TARGET_ARRIVAL)

    # 3. 最適化計算
    result_text = run_optimization(passengers, drivers, d_matrix, W)

    # 4. 結果出力
    print("\n--- 最終出力 ---")
    print(result_text)